version: '3.8'

services:
  audio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-button-grid
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      # Persystentny storage dla plików audio
      - audio_sounds:/app/public/sounds
      # Logi aplikacji
      - ./logs:/app/logs
    networks:
      - audio-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcjonalny Nginx reverse proxy (odkomentuj jeśli potrzebujesz)
  # nginx:
  #   image: nginx:alpine
  #   container_name: audio-app-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - audio-app
  #   networks:
  #     - audio-network

volumes:
  audio_sounds:
    driver: local

networks:
  audio-network:
    driver: bridge
